import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/ChakrsProviders";
import { Box } from "@chakra-ui/react";
import QueryClientProviderWrapper from "@/providers/ReactQuery";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProviderWrapper>
          <Providers>
            <Box className="my-5 mx-10">
              {children}
            </Box>
          </Providers>
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
